#!/usr/bin/env php
<?php
/**
 * cli模式下脚本执行入口
 * my --init 应用初始化
 * my [--run=指定应用目录] [m/]c/a ["b=1&d=1"|b=1 d=1]
 */

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    define('MY_RUN_DIR', __DIR__);
} else {
    if (file_exists(__DIR__ . '/../../autoload.php')) { // /vendor/myphps/myphp
        define('MY_RUN_DIR', realpath(__DIR__ . '/../../../'));
    } else {
        define('MY_RUN_DIR', __DIR__);
    }
}
//Phar包路径处理
if (class_exists(Phar::class, false) && Phar::running(false)) {
    define('MY_PHAR_PATH', Phar::running()); // phar://path/my.phar
    define('APP_RUN_DIR', dirname(Phar::running(false))); // /path/
} else {
    define('APP_RUN_DIR', MY_RUN_DIR);
}

$_arg = getopt('', ['run:', 'init']);
$init = isset($_arg['init']);
if ($init) { //初始化
    if (defined('MY_PHAR_PATH')) {
        die('Phar文档模式下不支持此操作!');
    }
    $_SERVER['argv'] = [];
    echo 'Run Dir: ' . APP_RUN_DIR, PHP_EOL;
} else {
    if (isset($_arg['run'])) { //myphp里会取$_SERVER['argv'][1]作为uri
        if ($_SERVER['argv'][1] == '--run') { // --run app
            unset($_SERVER['argv'][1], $_SERVER['argv'][2]);
        } else { // --run=app
            unset($_SERVER['argv'][1]);
        }
        $_SERVER['argv'] = array_values($_SERVER['argv']);
    }
}
//请求是有指定入口php文件 /xxx.php/c/a?d=1
if (!empty($_SERVER['argv'][1]) && $pos = strpos($_SERVER['argv'][1], '.php/')) {
    $run = substr($_SERVER['argv'][1], 0, $pos) . '.php';
    $_SERVER['argv'][1] = substr($_SERVER['argv'][1], $pos + 4); //请求地址处理
    //echo APP_RUN_DIR . '/web' . $run, PHP_EOL;
    #print_r($_SERVER);
    if (is_file(APP_RUN_DIR . '/web' . $run)) {
        require APP_RUN_DIR . '/web' . $run;
    } elseif (is_file(APP_RUN_DIR . $run)) {
        require APP_RUN_DIR . $run;
    } else {
        echo APP_RUN_DIR . '或' . APP_RUN_DIR . '/web目录下未找到' . $run . '文件';
    }
    exit();
}
//应用目录指定
$_app = trim($_arg['run'] ?? 'app', '/\\'); //默认 app
$_appDir = MY_RUN_DIR . '/' . $_app;
if (!$init && !is_dir($_appDir)) {
    die($_appDir . ' directory does not exist');
}
$_SERVER['IS_CLI_RUN'] = true;
define('APP_PATH', $_appDir);
define('COMMON', MY_RUN_DIR . '/common');
require MY_RUN_DIR . "/vendor/autoload.php";
if (is_file(APP_RUN_DIR . "/conf.php")) {
    require APP_RUN_DIR . "/conf.php";
}
//phar模式下路径处理
if (defined('MY_PHAR_PATH')) {
    //临时目录
    define('RUNTIME', APP_RUN_DIR . '/runtime');
    //站点目录
    define('SITE_WEB', APP_RUN_DIR . '/web');
    //日志目录
    empty($cfg['log_dir']) && $cfg['log_dir'] = APP_RUN_DIR . '/log';
}
require MY_RUN_DIR . "/vendor/myphps/myphp/base.php";
myphp::Run();
