<?php
namespace myphp;

class Request extends \HttpReqInfo{
    use \MyBaseObj;
/*
    public function rawBody()
    {
        return parent::rawBody(); // TODO: Change the autogenerated stub
    }

    public function setRawBody($rawBody)
    {
        parent::setRawBody($rawBody); // TODO: Change the autogenerated stub
    }*/
}