<?php
namespace myphp;

class Request extends \HttpReqInfo{
    public $expire = 0; //请求缓存过期时间 见 \myphp::$req_cache

/*
    public function rawBody()
    {
        return parent::rawBody(); // TODO: Change the autogenerated stub
    }

    public function setRawBody($rawBody)
    {
        parent::setRawBody($rawBody); // TODO: Change the autogenerated stub
    }*/
}